In [1]:
import pandas as pd

In [4]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [5]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   str
 2   homepage              1712 non-null   str
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   str
 5   original_language     4803 non-null   str
 6   original_title        4803 non-null   str
 7   overview              4800 non-null   str
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   str
 10  production_countries  4803 non-null   str
 11  release_date          4802 non-null   str
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   str
 15  status                4803 non-null   str
 16  tagline               3959 non-null   str
 17  title                 4803 non-null   str
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), str(13)
memory usage: 5.4 MB

In [6]:
credits.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   str
 2   cast      4803 non-null   str
 3   crew      4803 non-null   str
dtypes: int64(1), str(3)
memory usage: 33.8 MB

In [7]:
movies = movies[["id","genres","keywords","title","tagline","overview","production_companies"]]
credits = credits[["movie_id","cast","crew"]]

In [8]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    4803 non-null   int64
 1   genres                4803 non-null   str
 2   keywords              4803 non-null   str
 3   title                 4803 non-null   str
 4   tagline               3959 non-null   str
 5   overview              4800 non-null   str
 6   production_companies  4803 non-null   str
dtypes: int64(1), str(6)
memory usage: 4.1 MB

In [9]:
credits.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   cast      4803 non-null   str
 2   crew      4803 non-null   str
dtypes: int64(1), str(2)
memory usage: 33.7 MB

In [10]:
df = pd.merge(movies , credits , left_on = "id", right_on = "movie_id", how= 'inner')

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    4803 non-null   int64
 1   genres                4803 non-null   str
 2   keywords              4803 non-null   str
 3   title                 4803 non-null   str
 4   tagline               3959 non-null   str
 5   overview              4800 non-null   str
 6   production_companies  4803 non-null   str
 7   movie_id              4803 non-null   int64
 8   cast                  4803 non-null   str
 9   crew                  4803 non-null   str
dtypes: int64(2), str(8)
memory usage: 37.8 MB

In [12]:
df = df.drop(["movie_id"],axis = 1)
# df = df.drop(columns = ["movie_id"])
# df.drop(columns = ["movie_id"],inplace =True)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    4803 non-null   int64
 1   genres                4803 non-null   str
 2   keywords              4803 non-null   str
 3   title                 4803 non-null   str
 4   tagline               3959 non-null   str
 5   overview              4800 non-null   str
 6   production_companies  4803 non-null   str
 7   cast                  4803 non-null   str
 8   crew                  4803 non-null   str
dtypes: int64(1), str(8)
memory usage: 37.7 MB

In [14]:
desc = df.loc[0, 'genres']

In [15]:
desc

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [17]:
import ast
names = []
x = ast.literal_eval(desc)
# x = [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]
# item = {"id": 28, "name": "Action"}  when index = 0
# names = [Action,Adventure,Fantasy,Science Fiction]
for item in x:
    names.append(item['name'])
    comma_desc = ','.join(names)
comma_desc

'Action,Adventure,Fantasy,Science Fiction'

In [18]:
import ast
def get_names(desc):
    names = []
    x = ast.literal_eval(desc)
    for item in x:
        names.append(item['name'])
    
    comma_desc = ','.join(names)
    return comma_desc

In [19]:
df['genres'] = df['genres'].apply(get_names)

In [20]:
df['genres']
# [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]

0       Action,Adventure,Fantasy,Science Fiction
1                       Adventure,Fantasy,Action
2                         Action,Adventure,Crime
3                    Action,Crime,Drama,Thriller
4               Action,Adventure,Science Fiction
                          ...
4798                       Action,Crime,Thriller
4799                              Comedy,Romance
4800               Comedy,Drama,Romance,TV Movie
4801
4802                                 Documentary
Name: genres, Length: 4803, dtype: str

In [21]:
df['keywords'] = df['keywords'].apply(get_names)
df['cast'] = df['cast'].apply(get_names)
df['crew'] = df['crew'].apply(get_names)
df['production_companies'] = df['production_companies'].apply(get_names)

In [22]:
df.sample()

,id,genres,keywords,title,tagline,overview,production_companies,cast,crew
103,27022,"Fantasy,Adventure,Action,Comedy,Drama","witch,fire,wolf,fountain,magic,book,castle,wat...",The Sorcerer's Apprentice,It's The Coolest Job Ever.,Balthazar Blake is a master sorcerer in modern...,"Walt Disney Pictures,Jerry Bruckheimer Films,S...","Nicolas Cage,Jay Baruchel,Monica Bellucci,Alfr...","Jon Turteltaub,Scott Chestnut,Doug Miro,Carlo ..."

In [23]:
#need to replace space by '-' in production_companies, cast, crew because we want to treat them as single word while creating bag of words. 
# For example, if we have production company name as "Warner Bros", we want to treat it as "Warner-Bros" instead of two separate words "Warner" and "Bros". 
# So that we can get better recommendations.
# car journey => car-journey

df['genres'] = df['genres'].str.replace(' ', '-')
df['keywords'] = df['keywords'].str.replace(' ', '-')
df['production_companies'] = df['production_companies'].str.replace(' ', '-')
df['cast'] = df['cast'].str.replace(' ', '-')
df['crew'] = df['crew'].str.replace(' ', '-')

In [24]:
df.sample()

,id,genres,keywords,title,tagline,overview,production_companies,cast,crew
2723,25208,"Drama,Mystery,Thriller",woman-director,The Caveman's Valentine,NaN,In this spine-tingling and visually stunning t...,"Franchise-Pictures,Focus-Features,Jersey-Shore","Samuel-L.-Jackson,Colm-Feore,Ann-Magnuson,Aunj...","Kasi-Lemmons,George-Dawes-Green"

In [25]:
#Lets concatenate all columns except id, title
# bcz i need to create a vector matrix, it will be easy to find unique words,stopwords etc from one column.
df['tags'] = df['genres'] + ',' +  df['keywords'] + ',' + df['tagline'] + ',' + df['overview'] + ',' + df['production_companies'] + ',' + df['cast'] + ',' + df['crew']

In [26]:
df.loc[0,'tags']

"Action,Adventure,Fantasy,Science-Fiction,culture-clash,future,space-war,space-colony,society,space-travel,futuristic,romance,space,alien,tribe,alien-planet,cgi,marine,soldier,battle,love-affair,anti-war,power-relations,mind-and-soul,3d,Enter the World of Pandora.,In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.,Ingenious-Film-Partners,Twentieth-Century-Fox-Film-Corporation,Dune-Entertainment,Lightstorm-Entertainment,Sam-Worthington,Zoe-Saldana,Sigourney-Weaver,Stephen-Lang,Michelle-Rodriguez,Giovanni-Ribisi,Joel-David-Moore,CCH-Pounder,Wes-Studi,Laz-Alonso,Dileep-Rao,Matt-Gerald,Sean-Anthony-Moran,Jason-Whyte,Scott-Lawrence,Kelly-Kilgour,James-Patrick-Pitt,Sean-Patrick-Murphy,Peter-Dillon,Kevin-Dorman,Kelson-Henderson,David-Van-Horn,Jacob-Tomuri,Michael-Blain-Rozgay,Jon-Curry,Luke-Hawker,Woody-Schultz,Peter-Mensah,Sonia-Yee,Jahnel-Curfman,Ilram-Choi,Kyla-Warren,Lisa-Roumain,Debra-Wilson,Chris-Mala,Taylor-Kibby,Jodie-Landau,Julie-Lamm,Cullen-B.-Madden,Joseph-Brady-Madden,Frankie-Torres,Austin-Wilson,Sara-Wilson,Tamica-Washington-Miller,Lucy-Briant,Nathan-Meister,Gerry-Blair,Matthew-Chamberlain,Paul-Yates,Wray-Wilson,James-Gaylyn,Melvin-Leno-Clark-III,Carvon-Futrell,Brandon-Jelkes,Micah-Moch,Hanniyah-Muhammad,Christopher-Nolen,Christa-Oliver,April-Marie-Thomas,Bravita-A.-Threatt,Colin-Bleasdale,Mike-Bodnar,Matt-Clayton,Nicole-Dionne,Jamie-Harrison,Allan-Henry,Anthony-Ingruber,Ashley-Jeffery,Dean-Knowsley,Joseph-Mika-Hunt,Terry-Notary,Kai-Pantano,Logan-Pithyou,Stuart-Pollock,Raja,Gareth-Ruck,Rhian-Sheehan,T.-J.-Storm,Jodie-Taylor,Alicia-Vela-Bailey,Richard-Whiteside,Nikie-Zambo,Julene-Renee,Stephen-E.-Rivkin,Rick-Carter,Christopher-Boyes,Christopher-Boyes,Mali-Finn,James-Horner,James-Cameron,James-Cameron,James-Cameron,James-Cameron,James-Cameron,Andrew-Menzies,Jill-Brooks,Margery-Simkin,Kevin-Ishioka,Dick-Bernstein,Shannon-Mills,Dennie-Thorpe,Jana-Vance,Deborah-Lynn-Scott,Jon-Landau,Sean-Haworth,Kim-Sinclair,Kim-Sinclair,Richard-F.-Mays,Laeta-Kalogridis,Mayes-C.-Rubeo,Mauro-Fiore,Scott-Herbertson,Woody-Schultz,Linda-DeVetta,Linda-DeVetta,Richard-Bluck,Simon-Bright,Richard-Martin,Steve-R.-Moore,John-Refoua,Karl-J.-Martin,Chiling-Lin,Ilram-Choi,Steven-Quale,Carla-Meyer,Nick-Bassett,Jill-Cormack,Andy-McLaren,Terry-Notary,Garrett-Warren,Jonathan-Rothbart,Stefan-Dechant,Todd-Cherniawsky,Miranda-Rivers,Robert-Stromberg,John-Harding,Roberto-De-Angelis,Mike-Smithson,Alain-Lalanne,Lucas-Salton,Janace-Tashjian,Stephen-Rosenbaum,Frankie-Karena,Lisa-Lovaas,Jonathan-Fawkner,Robert-Bavin,Anthony-Almaraz,Carolyn-M.-Fenton,Beth-Koenigsberg,Sam-Page,Tex-Kadonaga,Kim-Foscato,Tammy-S.-Lee,Denny-Caira,James-Waitkus,Addison-Teague,C.-Scott-Baker,Luke-Caska,David-Chow,Jonathan-Dyer,Joseph-Hiura,Rebecca-Jellie,Robert-Andrew-Johnson,Mike-Stassi,John-Villarino,Jeffrey-Wisniewski,Cheryl-Nardi,Marshall-Winn,Gwendolyn-Yates-Whittle,William-Stein,Lula-Washington,Chris-Del-Conte,R.-Christopher-White,Dan-Lemmon,Tim-Nielsen,Michael-Mulholland,Thomas-Nittmann,Edson-Williams,Christine-Carr,John-Bruno,David-Emmerichs,Christopher-Scarabosio,Jennifer-Teves,Brigitte-Yorke,Ken-Fischer,Iain-Hutton,Steve-Ingram,Joyce-Cox,Jenny-Foster,Christopher-Marino,Jim-Milton,Cyndi-Ochs,Lucas-Putnam,Anthony-'Max'-Ivins,John-Knoll,Eric-Saindon,Wayne-Stables,David-Stinnett,Guy-Williams,Stuart-Thorp,Giles-Coburn,Mark-Fellman,Scott-Sprague,Jeremy-Hollobon,Orlando-Meunier,Taisuke-Tanimura,Lilia-Mishel-Acevedo,Alejandro-M.-Hernandez,Marvin-Hall,Judy-Alley,Mike-Perry,Andrew-Morley,Seth-Engstrom,Eric-Oliver,Matsune-Suzuki,Paul-Tobin,Roxane-Griffin,Arun-Ram-Mohan,Georgia-Lockhart-Adams,Thrain-Shadbolt,Brad-Alexander,Shadi-Almassizadeh,Simon-Clutterbuck,Graeme-Demmocks,Adrian-Fernandes,Mitch-Gates,Jerry-Kung,Andy-Lomas,Sebastian-Marino,Matthias-Menz,Sergei-Nevshupov,Philippe-Rebours,Michael-Takarangi,David-Weitzberg,Ben-White,Min-Windle"

In [27]:
df = df[["id","title","tags"]]

In [28]:
# df

In [29]:
df['tags'] = df['tags'].str.lower()

In [30]:
df

,id,title,tags
0,19995,Avatar,"action,adventure,fantasy,science-fiction,cultu..."
1,285,Pirates of the Caribbean: At World's End,"adventure,fantasy,action,ocean,drug-abuse,exot..."
2,206647,Spectre,"action,adventure,crime,spy,based-on-novel,secr..."
3,49026,The Dark Knight Rises,"action,crime,drama,thriller,dc-comics,crime-fi..."
4,49529,John Carter,"action,adventure,science-fiction,based-on-nove..."
...,...,...,...
4798,9367,El Mariachi,"action,crime,thriller,united-states–mexico-bar..."
4799,72766,Newlyweds,"comedy,romance,,a newlywed couple's honeymoon ..."
4800,231617,"Signed, Sealed, Delivered",NaN
4801,126186,Shanghai Calling,",,a new yorker in shanghai,when ambitious new ..."
4802,25975,My Date with Drew,NaN

In [31]:
df['tags'] = df['tags'].str.replace('.', '')

In [32]:
df.loc[0,'tags']

"action,adventure,fantasy,science-fiction,culture-clash,future,space-war,space-colony,society,space-travel,futuristic,romance,space,alien,tribe,alien-planet,cgi,marine,soldier,battle,love-affair,anti-war,power-relations,mind-and-soul,3d,enter the world of pandora,in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization,ingenious-film-partners,twentieth-century-fox-film-corporation,dune-entertainment,lightstorm-entertainment,sam-worthington,zoe-saldana,sigourney-weaver,stephen-lang,michelle-rodriguez,giovanni-ribisi,joel-david-moore,cch-pounder,wes-studi,laz-alonso,dileep-rao,matt-gerald,sean-anthony-moran,jason-whyte,scott-lawrence,kelly-kilgour,james-patrick-pitt,sean-patrick-murphy,peter-dillon,kevin-dorman,kelson-henderson,david-van-horn,jacob-tomuri,michael-blain-rozgay,jon-curry,luke-hawker,woody-schultz,peter-mensah,sonia-yee,jahnel-curfman,ilram-choi,kyla-warren,lisa-roumain,debra-wilson,chris-mala,taylor-kibby,jodie-landau,julie-lamm,cullen-b-madden,joseph-brady-madden,frankie-torres,austin-wilson,sara-wilson,tamica-washington-miller,lucy-briant,nathan-meister,gerry-blair,matthew-chamberlain,paul-yates,wray-wilson,james-gaylyn,melvin-leno-clark-iii,carvon-futrell,brandon-jelkes,micah-moch,hanniyah-muhammad,christopher-nolen,christa-oliver,april-marie-thomas,bravita-a-threatt,colin-bleasdale,mike-bodnar,matt-clayton,nicole-dionne,jamie-harrison,allan-henry,anthony-ingruber,ashley-jeffery,dean-knowsley,joseph-mika-hunt,terry-notary,kai-pantano,logan-pithyou,stuart-pollock,raja,gareth-ruck,rhian-sheehan,t-j-storm,jodie-taylor,alicia-vela-bailey,richard-whiteside,nikie-zambo,julene-renee,stephen-e-rivkin,rick-carter,christopher-boyes,christopher-boyes,mali-finn,james-horner,james-cameron,james-cameron,james-cameron,james-cameron,james-cameron,andrew-menzies,jill-brooks,margery-simkin,kevin-ishioka,dick-bernstein,shannon-mills,dennie-thorpe,jana-vance,deborah-lynn-scott,jon-landau,sean-haworth,kim-sinclair,kim-sinclair,richard-f-mays,laeta-kalogridis,mayes-c-rubeo,mauro-fiore,scott-herbertson,woody-schultz,linda-devetta,linda-devetta,richard-bluck,simon-bright,richard-martin,steve-r-moore,john-refoua,karl-j-martin,chiling-lin,ilram-choi,steven-quale,carla-meyer,nick-bassett,jill-cormack,andy-mclaren,terry-notary,garrett-warren,jonathan-rothbart,stefan-dechant,todd-cherniawsky,miranda-rivers,robert-stromberg,john-harding,roberto-de-angelis,mike-smithson,alain-lalanne,lucas-salton,janace-tashjian,stephen-rosenbaum,frankie-karena,lisa-lovaas,jonathan-fawkner,robert-bavin,anthony-almaraz,carolyn-m-fenton,beth-koenigsberg,sam-page,tex-kadonaga,kim-foscato,tammy-s-lee,denny-caira,james-waitkus,addison-teague,c-scott-baker,luke-caska,david-chow,jonathan-dyer,joseph-hiura,rebecca-jellie,robert-andrew-johnson,mike-stassi,john-villarino,jeffrey-wisniewski,cheryl-nardi,marshall-winn,gwendolyn-yates-whittle,william-stein,lula-washington,chris-del-conte,r-christopher-white,dan-lemmon,tim-nielsen,michael-mulholland,thomas-nittmann,edson-williams,christine-carr,john-bruno,david-emmerichs,christopher-scarabosio,jennifer-teves,brigitte-yorke,ken-fischer,iain-hutton,steve-ingram,joyce-cox,jenny-foster,christopher-marino,jim-milton,cyndi-ochs,lucas-putnam,anthony-'max'-ivins,john-knoll,eric-saindon,wayne-stables,david-stinnett,guy-williams,stuart-thorp,giles-coburn,mark-fellman,scott-sprague,jeremy-hollobon,orlando-meunier,taisuke-tanimura,lilia-mishel-acevedo,alejandro-m-hernandez,marvin-hall,judy-alley,mike-perry,andrew-morley,seth-engstrom,eric-oliver,matsune-suzuki,paul-tobin,roxane-griffin,arun-ram-mohan,georgia-lockhart-adams,thrain-shadbolt,brad-alexander,shadi-almassizadeh,simon-clutterbuck,graeme-demmocks,adrian-fernandes,mitch-gates,jerry-kung,andy-lomas,sebastian-marino,matthias-menz,sergei-nevshupov,philippe-rebours,michael-takarangi,david-weitzberg,ben-white,min-windle"

In [33]:
df['tags'].shape

(4803,)

In [ ]:
df.to_csv("cleaned_data1.csv",index = False)