In [7]:
import pandas as pd

In [8]:
credits = pd.read_csv("tmdb_5000_credits.csv")
movies = pd.read_csv("tmdb_5000_movies.csv")

In [9]:
credits.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   str
 2   cast      4803 non-null   str
 3   crew      4803 non-null   str
dtypes: int64(1), str(3)
memory usage: 33.8 MB

In [10]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   str
 2   homepage              1712 non-null   str
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   str
 5   original_language     4803 non-null   str
 6   original_title        4803 non-null   str
 7   overview              4800 non-null   str
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   str
 10  production_countries  4803 non-null   str
 11  release_date          4802 non-null   str
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   str
 15  status                4803 non-null   str
 16  tagline               3959 non-null   str
 17  title                 4803 non-null   str
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), str(13)
memory usage: 5.4 MB

In [11]:
movies = movies[["id","genres","keywords","title","tagline","overview","production_companies"]]
credits = credits[["movie_id","cast","crew"]]

In [12]:
credits.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   cast      4803 non-null   str
 2   crew      4803 non-null   str
dtypes: int64(1), str(2)
memory usage: 33.7 MB

In [13]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    4803 non-null   int64
 1   genres                4803 non-null   str
 2   keywords              4803 non-null   str
 3   title                 4803 non-null   str
 4   tagline               3959 non-null   str
 5   overview              4800 non-null   str
 6   production_companies  4803 non-null   str
dtypes: int64(1), str(6)
memory usage: 4.1 MB

In [14]:
df = pd.merge(movies, credits, left_on='id', right_on='movie_id', how='inner')

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    4803 non-null   int64
 1   genres                4803 non-null   str
 2   keywords              4803 non-null   str
 3   title                 4803 non-null   str
 4   tagline               3959 non-null   str
 5   overview              4800 non-null   str
 6   production_companies  4803 non-null   str
 7   movie_id              4803 non-null   int64
 8   cast                  4803 non-null   str
 9   crew                  4803 non-null   str
dtypes: int64(2), str(8)
memory usage: 37.8 MB

In [16]:
df = df.drop(columns = ["movie_id"])

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    4803 non-null   int64
 1   genres                4803 non-null   str
 2   keywords              4803 non-null   str
 3   title                 4803 non-null   str
 4   tagline               3959 non-null   str
 5   overview              4800 non-null   str
 6   production_companies  4803 non-null   str
 7   cast                  4803 non-null   str
 8   crew                  4803 non-null   str
dtypes: int64(1), str(8)
memory usage: 37.7 MB

In [18]:
desc = df.loc[2, 'genres']

In [19]:

 [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 80, "name": "Crime"}]

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 80, 'name': 'Crime'}]

In [20]:
import ast
names = []
x = ast.literal_eval(desc)
for item in x:
     names.append(item['name'])
    
comma_desc = ','.join(names)
comma_desc

'Action,Adventure,Crime'

In [21]:
df.sample()

,id,genres,keywords,title,tagline,overview,production_companies,cast,crew
3073,2088,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 4668, ""name"": ""police operation""}, {""i...",Romeo Is Bleeding,The story of a cop who wanted it bad and got i...,A corrupt cop gets in over his head when he tr...,"[{""name"": ""Working Title Films"", ""id"": 10163},...","[{""cast_id"": 11, ""character"": ""Jack Grimaldi"",...","[{""credit_id"": ""52fe4334c3a36847f80422ef"", ""de..."

In [22]:
import ast

def get_names(desc):
      names = []
      
      x = ast.literal_eval(desc)
      for item in x:
          names.append(item['name'])
      comma_desc = ','.join(names)
      return comma_desc

In [23]:
df['genres'] = df['genres'].apply(get_names)

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    4803 non-null   int64
 1   genres                4803 non-null   str
 2   keywords              4803 non-null   str
 3   title                 4803 non-null   str
 4   tagline               3959 non-null   str
 5   overview              4800 non-null   str
 6   production_companies  4803 non-null   str
 7   cast                  4803 non-null   str
 8   crew                  4803 non-null   str
dtypes: int64(1), str(8)
memory usage: 37.5 MB

In [25]:
df['genres']

0       Action,Adventure,Fantasy,Science Fiction
1                       Adventure,Fantasy,Action
2                         Action,Adventure,Crime
3                    Action,Crime,Drama,Thriller
4               Action,Adventure,Science Fiction
                          ...
4798                       Action,Crime,Thriller
4799                              Comedy,Romance
4800               Comedy,Drama,Romance,TV Movie
4801
4802                                 Documentary
Name: genres, Length: 4803, dtype: str

In [26]:
df.sample()

,id,genres,keywords,title,tagline,overview,production_companies,cast,crew
3895,158015,"Science Fiction,Horror,Thriller","[{""id"": 4565, ""name"": ""dystopia""}, {""id"": 7246...",The Purge,"One night a year, all crime is legal.","Given the country's overcrowded prisons, the U...","[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...","[{""cast_id"": 3, ""character"": ""Mary Sandin"", ""c...","[{""credit_id"": ""52fe4bd99251416c910e79ab"", ""de..."

In [31]:
df['genres'] = df['genres'].str.replace(' ', '-')
df['keywords'] = df['keywords'].str.replace(' ', '-')
df['production_companies'] = df['production_companies'].str.replace(' ', '-')
df['cast'] = df['cast'].str.replace(' ', '-')
df['crew'] = df['crew'].str.replace(' ', '-')

In [32]:
df.sample()

,id,genres,keywords,title,tagline,overview,production_companies,cast,crew
2698,24940,"Comedy,Romance","[{""id"":-4522,-""name"":-""supermodel""},-{""id"":-10...",Head Over Heels,Unleash your inner model.,Ordinary single girl Amanda Pierce (Monica Pot...,"[{""name"":-""Universal-Studios"",-""id"":-13}]","[{""cast_id"":-1,-""character"":-""Amanda-Pierce"",-...","[{""credit_id"":-""52fe44b1c3a368484e031709"",-""de..."

In [35]:
df.fillna('',inplace = True)

,id,genres,keywords,title,tagline,overview,production_companies,cast,crew
0,19995,"Action,Adventure,Fantasy,Science-Fiction","[{""id"":-1463,-""name"":-""culture-clash""},-{""id"":...",Avatar,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...","[{""name"":-""Ingenious-Film-Partners"",-""id"":-289...","[{""cast_id"":-242,-""character"":-""Jake-Sully"",-""...","[{""credit_id"":-""52fe48009251416c750aca23"",-""de..."
1,285,"Adventure,Fantasy,Action","[{""id"":-270,-""name"":-""ocean""},-{""id"":-726,-""na...",Pirates of the Caribbean: At World's End,"At the end of the world, the adventure begins.","Captain Barbossa, long believed to be dead, ha...","[{""name"":-""Walt-Disney-Pictures"",-""id"":-2},-{""...","[{""cast_id"":-4,-""character"":-""Captain-Jack-Spa...","[{""credit_id"":-""52fe4232c3a36847f800b579"",-""de..."
2,206647,"Action,Adventure,Crime","[{""id"":-470,-""name"":-""spy""},-{""id"":-818,-""name...",Spectre,A Plan No One Escapes,A cryptic message from Bond’s past sends him o...,"[{""name"":-""Columbia-Pictures"",-""id"":-5},-{""nam...","[{""cast_id"":-1,-""character"":-""James-Bond"",-""cr...","[{""credit_id"":-""54805967c3a36829b5002c41"",-""de..."
3,49026,"Action,Crime,Drama,Thriller","[{""id"":-849,-""name"":-""dc-comics""},-{""id"":-853,...",The Dark Knight Rises,The Legend Ends,Following the death of District Attorney Harve...,"[{""name"":-""Legendary-Pictures"",-""id"":-923},-{""...","[{""cast_id"":-2,-""character"":-""Bruce-Wayne-/-Ba...","[{""credit_id"":-""52fe4781c3a36847f81398c3"",-""de..."
4,49529,"Action,Adventure,Science-Fiction","[{""id"":-818,-""name"":-""based-on-novel""},-{""id"":...",John Carter,"Lost in our world, found in another.","John Carter is a war-weary, former military ca...","[{""name"":-""Walt-Disney-Pictures"",-""id"":-2}]","[{""cast_id"":-5,-""character"":-""John-Carter"",-""c...","[{""credit_id"":-""52fe479ac3a36847f813eaa3"",-""de..."
...,...,...,...,...,...,...,...,...,...
4798,9367,"Action,Crime,Thriller","[{""id"":-5616,-""name"":-""united-states\u2013mexi...",El Mariachi,"He didn't come looking for trouble, but troubl...",El Mariachi just wants to play his guitar and ...,"[{""name"":-""Columbia-Pictures"",-""id"":-5}]","[{""cast_id"":-1,-""character"":-""El-Mariachi"",-""c...","[{""credit_id"":-""52fe44eec3a36847f80b280b"",-""de..."
4799,72766,"Comedy,Romance",[],Newlyweds,A newlywed couple's honeymoon is upended by th...,A newlywed couple's honeymoon is upended by th...,[],"[{""cast_id"":-1,-""character"":-""Buzzy"",-""credit_...","[{""credit_id"":-""52fe487dc3a368484e0fb013"",-""de..."
4800,231617,"Comedy,Drama,Romance,TV-Movie","[{""id"":-248,-""name"":-""date""},-{""id"":-699,-""nam...","Signed, Sealed, Delivered",,"""Signed, Sealed, Delivered"" introduces a dedic...","[{""name"":-""Front-Street-Pictures"",-""id"":-3958}...","[{""cast_id"":-8,-""character"":-""Oliver-O\u2019To...","[{""credit_id"":-""52fe4df3c3a36847f8275ecf"",-""de..."
4801,126186,,[],Shanghai Calling,A New Yorker in Shanghai,When ambitious New York attorney Sam is sent t...,[],"[{""cast_id"":-3,-""character"":-""Sam"",-""credit_id...","[{""credit_id"":-""52fe4ad9c3a368484e16a36b"",-""de..."
4802,25975,Documentary,"[{""id"":-1523,-""name"":-""obsession""},-{""id"":-224...",My Date with Drew,,Ever since the second grade when he first saw ...,"[{""name"":-""rusty-bear-entertainment"",-""id"":-87...","[{""cast_id"":-3,-""character"":-""Herself"",-""credi...","[{""credit_id"":-""58ce021b9251415a390165d9"",-""de..."

In [43]:
df.columns

Index(['id', 'genres', 'keywords', 'title', 'tagline', 'overview',
       'production_companies', 'cast', 'crew'],
      dtype='str')

In [48]:
df['tags']=(
    df['overview']+''+
    df['genres']+''+
    df['keywords']+''+
    df['cast']+''+
    df['crew'])

In [49]:
df[['id','title','tags']]

,id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4798,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4799,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4800,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4801,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4802,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    4803 non-null   int64
 1   genres                4803 non-null   str
 2   keywords              4803 non-null   str
 3   title                 4803 non-null   str
 4   tagline               4803 non-null   str
 5   overview              4803 non-null   str
 6   production_companies  4803 non-null   str
 7   cast                  4803 non-null   str
 8   crew                  4803 non-null   str
 9   tags                  4803 non-null   str
dtypes: int64(1), str(9)
memory usage: 73.8 MB

In [51]:
"df['tags'] = df['tags'].str.lower()"

"df['tags'] = df['tags'].str.lower()"

In [52]:
df.loc[0,'tags']

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.Action,Adventure,Fantasy,Science-Fiction[{"id":-1463,-"name":-"culture-clash"},-{"id":-2964,-"name":-"future"},-{"id":-3386,-"name":-"space-war"},-{"id":-3388,-"name":-"space-colony"},-{"id":-3679,-"name":-"society"},-{"id":-3801,-"name":-"space-travel"},-{"id":-9685,-"name":-"futuristic"},-{"id":-9840,-"name":-"romance"},-{"id":-9882,-"name":-"space"},-{"id":-9951,-"name":-"alien"},-{"id":-10148,-"name":-"tribe"},-{"id":-10158,-"name":-"alien-planet"},-{"id":-10987,-"name":-"cgi"},-{"id":-11399,-"name":-"marine"},-{"id":-13065,-"name":-"soldier"},-{"id":-14643,-"name":-"battle"},-{"id":-14720,-"name":-"love-affair"},-{"id":-165431,-"name":-"anti-war"},-{"id":-193554,-"name":-"power-relations"},-{"id":-206690,-"name":-"mind-and-soul"},-{"id":-209714,-"name":-"3d"}][{"cast_id":-242,-"character":-"Jake-Sully",-"credit_id":-"5602a8a7c3a3685532001c9a",-"gender":-2,-"id":-65731,-"name":-"Sam-Worthington",-"order":-0},-{"cast_id":-3,-"character":-"Neytiri",-"credit_id":-"52fe48009251416c750ac9cb",-"gender":-1,-"id":-8691,-"name":-"Zoe-Saldana",-"order":-1},-{"cast_id":-25,-"character":-"Dr.-Grace-Augustine",-"credit_id":-"52fe48009251416c750aca39",-"gender":-1,-"id":-10205,-"name":-"Sigourney-Weaver",-"order":-2},-{"cast_id":-4,-"character":-"Col.-Quaritch",-"credit_id":-"52fe48009251416c750ac9cf",-"gender":-2,-"id":-32747,-"name":-"Stephen-Lang",-"order":-3},-{"cast_id":-5,-"character":-"Trudy-Chacon",-"credit_id":-"52fe48009251416c750ac9d3",-"gender":-1,-"id":-17647,-"name":-"Michelle-Rodriguez",-"order":-4},-{"cast_id":-8,-"character":-"Selfridge",-"credit_id":-"52fe48009251416c750ac9e1",-"gender":-2,-"id":-1771,-"name":-"Giovanni-Ribisi",-"order":-5},-{"cast_id":-7,-"character":-"Norm-Spellman",-"credit_id":-"52fe48009251416c750ac9dd",-"gender":-2,-"id":-59231,-"name":-"Joel-David-Moore",-"order":-6},-{"cast_id":-9,-"character":-"Moat",-"credit_id":-"52fe48009251416c750ac9e5",-"gender":-1,-"id":-30485,-"name":-"CCH-Pounder",-"order":-7},-{"cast_id":-11,-"character":-"Eytukan",-"credit_id":-"52fe48009251416c750ac9ed",-"gender":-2,-"id":-15853,-"name":-"Wes-Studi",-"order":-8},-{"cast_id":-10,-"character":-"Tsu\'Tey",-"credit_id":-"52fe48009251416c750ac9e9",-"gender":-2,-"id":-10964,-"name":-"Laz-Alonso",-"order":-9},-{"cast_id":-12,-"character":-"Dr.-Max-Patel",-"credit_id":-"52fe48009251416c750ac9f1",-"gender":-2,-"id":-95697,-"name":-"Dileep-Rao",-"order":-10},-{"cast_id":-13,-"character":-"Lyle-Wainfleet",-"credit_id":-"52fe48009251416c750ac9f5",-"gender":-2,-"id":-98215,-"name":-"Matt-Gerald",-"order":-11},-{"cast_id":-32,-"character":-"Private-Fike",-"credit_id":-"52fe48009251416c750aca5b",-"gender":-2,-"id":-154153,-"name":-"Sean-Anthony-Moran",-"order":-12},-{"cast_id":-33,-"character":-"Cryo-Vault-Med-Tech",-"credit_id":-"52fe48009251416c750aca5f",-"gender":-2,-"id":-397312,-"name":-"Jason-Whyte",-"order":-13},-{"cast_id":-34,-"character":-"Venture-Star-Crew-Chief",-"credit_id":-"52fe48009251416c750aca63",-"gender":-2,-"id":-42317,-"name":-"Scott-Lawrence",-"order":-14},-{"cast_id":-35,-"character":-"Lock-Up-Trooper",-"credit_id":-"52fe48009251416c750aca67",-"gender":-2,-"id":-986734,-"name":-"Kelly-Kilgour",-"order":-15},-{"cast_id":-36,-"character":-"Shuttle-Pilot",-"credit_id":-"52fe48009251416c750aca6b",-"gender":-0,-"id":-1207227,-"name":-"James-Patrick-Pitt",-"order":-16},-{"cast_id":-37,-"character":-"Shuttle-Co-Pilot",-"credit_id":-"52fe48009251416c750aca6f",-"gender":-0,-"id":-1180936,-"name":-"Sean-Patrick-Murphy",-"order":-17},-{"cast_id":-38,-"character":-"Shuttle-Crew-Chief",-"credit_id":-"52fe48009251416c750aca73",-"gender":-2,-"id":-1019578,-"name":-"Peter-Dillon",-"order":-18},-{"cast_id":-39,-"character":-"Tractor-Operator-/-Troupe",-"credit_id":-"52fe48009251416c750aca77",-"gender":-0,-"id":-91443,-"name":-"Kevin-Dorman",-"order":-19},-{"cast_id":-40,-"character":-"Dragon-Gunship-Pilot",-"credit_id":-"52fe48009251416c750aca7b",-"gender":-2,-"id":-173391,-"name":-"Kelson-Henderson",-"order":-20},-{"cast_id":-41,-"character":-"Dragon-Gunship-Gunner",-"credit_id":-"52fe48009251416c750aca7f",-"gender":-0,-"id":-1207236,-"name":-"David-Van-Horn",-"order":-21},-{"cast_id":-42,-"character":-"Dragon-Gunship-Navigator",-"credit_id":-"52fe48009251416c750aca83",-"gender":-0,-"id":-215913,-"name":-"Jacob-Tomuri",-"order":-22},-{"cast_id":-43,-"character":-"Suit-#1",-"credit_id":-"52fe48009251416c750aca87",-"gender":-0,-"id":-143206,-"name":-"Michael-Blain-Rozgay",-"order":-23},-{"cast_id":-44,-"character":-"Suit-#2",-"credit_id":-"52fe48009251416c750aca8b",-"gender":-2,-"id":-169676,-"name":-"Jon-Curry",-"order":-24},-{"cast_id":-46,-"character":-"Ambient-Room-Tech",-"credit_id":-"52fe48009251416c750aca8f",-"gender":-0,-"id":-1048610,-"name":-"Luke-Hawker",-"order":-25},-{"cast_id":-47,-"character":-"Ambient-Room-Tech-/-Troupe",-"credit_id":-"52fe48009251416c750aca93",-"gender":-0,-"id":-42288,-"name":-"Woody-Schultz",-"order":-26},-{"cast_id":-48,-"character":-"Horse-Clan-Leader",-"credit_id":-"52fe48009251416c750aca97",-"gender":-2,-"id":-68278,-"name":-"Peter-Mensah",-"order":-27},-{"cast_id":-49,-"character":-"Link-Room-Tech",-"credit_id":-"52fe48009251416c750aca9b",-"gender":-0,-"id":-1207247,-"name":-"Sonia-Yee",-"order":-28},-{"cast_id":-50,-"character":-"Basketball-Avatar-/-Troupe",-"credit_id":-"52fe48009251416c750aca9f",-"gender":-1,-"id":-1207248,-"name":-"Jahnel-Curfman",-"order":-29},-{"cast_id":-51,-"character":-"Basketball-Avatar",-"credit_id":-"52fe48009251416c750acaa3",-"gender":-0,-"id":-89714,-"name":-"Ilram-Choi",-"order":-30},-{"cast_id":-52,-"character":-"Na\'vi-Child",-"credit_id":-"52fe48009251416c750acaa7",-"gender":-0,-"id":-1207249,-"name":-"Kyla-Warren",-"order":-31},-{"cast_id":-53,-"character":-"Troupe",-"credit_id":-"52fe48009251416c750acaab",-"gender":-0,-"id":-1207250,-"name":-"Lisa-Roumain",-"order":-32},-{"cast_id":-54,-"character":-"Troupe",-"credit_id":-"52fe48009251416c750acaaf",-"gender":-1,-"id":-83105,-"name":-"Debra-Wilson",-"order":-33},-{"cast_id":-57,-"character":-"Troupe",-"credit_id":-"52fe48009251416c750acabb",-"gender":-0,-"id":-1207253,-"name":-"Chris-Mala",-"order":-34},-{"cast_id":-55,-"character":-"Troupe",-"credit_id":-"52fe48009251416c750acab3",-"gender":-0,-"id":-1207251,-"name":-"Taylor-Kibby",-"order":-35},-{"cast_id":-56,-"character":-"Troupe",-"credit_id":-"52fe48009251416c750acab7",-"gender":-0,-"id":-1207252,-"name":-"Jodie-Landau",-"order":-36},-{"cast_id":-58,-"character":-"Troupe",-"credit_id":-"52fe48009251416c750acabf",-"gender":-0,-"id":-1207254,-"name":-"Julie-Lamm",-"order":-37},-{"cast_id":-59,-"character":-"Troupe",-"credit_id":-"52fe48009251416c750acac3",-"gender":-0,-"id":-1207257,-"name":-"Cullen-B.-Madden",-"order":-38},-{"cast_id":-60,-"character":-"Troupe",-"credit_id":-"52fe48009251416c750acac7",-"gender":-0,-"id":-1207259,-"name":-"Joseph-Brady-Madden",-"order":-39},-{"cast_id":-61,-"character":-"Troupe",-"credit_id":-"52fe48009251416c750acacb",-"gender":-0,-"id":-1207262,-"name":-"Frankie-Torres",-"order":-40},-{"cast_id":-62,-"character":-"Troupe",-"credit_id":-"52fe48009251416c750acacf",-"gender":-1,-"id":-1158600,-"name":-"Austin-Wilson",-"order":-41},-{"cast_id":-63,-"character":-"Troupe",-"credit_id":-"52fe48019251416c750acad3",-"gender":-1,-"id":-983705,-"name":-"Sara-Wilson",-"order":-42},-{"cast_id":-64,-"character":-"Troupe",-"credit_id":-"52fe48019251416c750acad7",-"gender":-0,-"id":-1207263,-"name":-"Tamica-Washington-Miller",-"order":-43},-{"cast_id":-65,-"character":-"Op-Center-Staff",-"credit_id":-"52fe48019251416c750acadb",-"gender":-1,-"id":-1145098,-"name":-"Lucy-Briant",-"order":-44},-{"cast_id":-66,-"character":-"Op-Center-Staff",-"credit_id":-"52fe48019251416c750acadf",-"gender":-2,-"id":-33305,-"name":-"Nathan-Meister",-"order":-45},-{"cast_id":-67,-"character":-"Op-Center-Staff",-"credit_id":-"52fe48019251416c750acae3",-"gender":-0,-"id":-1207264,-"name":-"Gerry-Blair",-"order":-46},-{"cast_id":-68,-"character":-"Op-Center-Staff",-"credit_id":-"52fe48019251416c750acae7",-"gender":-2,-"id":-33311,-"name":-"Matthew-Chamberlain",-"order":-47},-{"cast_id":-69,-"character":-"Op-Center-Staff",-"credit_id":-"52fe48019251416c750acaeb",-"gender":-0,-"id":-1207265,-"name":-"Paul-Yates",-"order":-48},-{"cast_id":-70,-"character":-"Op-Center-Duty-Officer",-"credit_id":-"52fe48019251416c750acaef",-"gender":-0,-"id":-1207266,-"name":-"Wray-Wilson",-"order":-49},-{"cast_id":-71,-"character":-"Op-Center-Staff",-"credit_id":-"52fe48019251416c750acaf3",-"gender":-2,-"id":-54492,-"name":-"James-Gaylyn",-"order":-50},-{"cast_id":-72,-"character":-"Dancer",-"credit_id":-"52fe48019251416c750acaf7",-"gender":-0,-"id":-1207267,-"name":-"Melvin-Leno-Clark-III",-"order":-51},-{"cast_id":-73,-"character":-"Dancer",-"credit_id":-"52fe48019251416c750acafb",-"gender":-0,-"id":-1207268,-"name":-"Carvon-Futrell",-"order":-52},-{"cast_id":-74,-"character":-"Dancer",-"credit_id":-"52fe48019251416c750acaff",-"gender":-0,-"id":-1207269,-"name":-"Brandon-Jelkes",-"order":-53},-{"cast_id":-75,-"character":-"Dancer",-"credit_id":-"52fe48019251416c750acb03",-"gender":-0,-"id":-1207270,-"name":-"Micah-Moch",-"order":-54},-{"cast_id":-76,-"character":-"Dancer",-"credit_id":-"52fe48019251416c750acb07",-"gender":-0,-"id":-1207271,-"name":-"Hanniyah-Muhammad",-"order":-55},-{"cast_id":-77,-"character":-"Dancer",-"credit_id":-"52fe48019251416c750acb0b",-"gender":-0,-"id":-1207272,-"name":-"Christopher-Nolen",-"order":-56},-{"cast_id":-78,-"character":-"Dancer",-"credit_id":-"52fe48019251416c750acb0f",-"gender":-0,-"id":-1207273,-"name":-"Christa-Oliver",-"order":-57},-{"cast_id":-79,-"character":-"Dancer",-"credit_id":-"52fe48019251416c750acb13",-"gender":-0,-"id":-1207274,-"name":-"April-Marie-Thomas",-"order":-58},-{"cast_id":-80,-"character":-"Dancer",-"credit_id":-"52fe48019251416c750acb17",-"gender":-0,-"id":-1207275,-"name":-"Bravita-A.-Threatt",-"order":-59},-{"cast_id":-81,-"character":-"Mining-Chief-(uncredited)",-"credit_id":-"52fe48019251416c750acb1b",-"gender":-0,-"id":-1207276,-"name":-"Colin-Bleasdale",-"order":-60},-{"cast_id":-82,-"character":-"Veteran-Miner-(uncredited)",-"credit_id":-"52fe48019251416c750acb1f",-"gender":-0,-"id":-107969,-"name":-"Mike-Bodnar",-"order":-61},-{"cast_id":-83,-"character":-"Richard-(uncredited)",-"credit_id":-"52fe48019251416c750acb23",-"gender":-0,-"id":-1207278,-"name":-"Matt-Clayton",-"order":-62},-{"cast_id":-84,-"character":-"Nav\'i-(uncredited)",-"credit_id":-"52fe48019251416c750acb27",-"gender":-1,-"id":-147898,-"name":-"Nicole-Dionne",-"order":-63},-{"cast_id":-85,-"character":-"Trooper-(uncredited)",-"credit_id":-"52fe48019251416c750acb2b",-"gender":-0,-"id":-1207280,-"name":-"Jamie-Harrison",-"order":-64},-{"cast_id":-86,-"character":-"Trooper-(uncredited)",-"credit_id":-"52fe48019251416c750acb2f",-"gender":-0,-"id":-1207281,-"name":-"Allan-Henry",-"order":-65},-{"cast_id":-87,-"character":-"Ground-Technician-(uncredited)",-"credit_id":-"52fe48019251416c750acb33",-"gender":-2,-"id":-1207282,-"name":-"Anthony-Ingruber",-"order":-66},-{"cast_id":-88,-"character":-"Flight-Crew-Mechanic-(uncredited)",-"credit_id":-"52fe48019251416c750acb37",-"gender":-0,-"id":-1207283,-"name":-"Ashley-Jeffery",-"order":-67},-{"cast_id":-14,-"character":-"Samson-Pilot",-"credit_id":-"52fe48009251416c750ac9f9",-"gender":-0,-"id":-98216,-"name":-"Dean-Knowsley",-"order":-68},-{"cast_id":-89,-"character":-"Trooper-(uncredited)",-"credit_id":-"52fe48019251416c750acb3b",-"gender":-0,-"id":-1201399,-"name":-"Joseph-Mika-Hunt",-"order":-69},-{"cast_id":-90,-"character":-"Banshee-(uncredited)",-"credit_id":-"52fe48019251416c750acb3f",-"gender":-0,-"id":-236696,-"name":-"Terry-Notary",-"order":-70},-{"cast_id":-91,-"character":-"Soldier-(uncredited)",-"credit_id":-"52fe48019251416c750acb43",-"gender":-0,-"id":-1207287,-"name":-"Kai-Pantano",-"order":-71},-{"cast_id":-92,-"character":-"Blast-Technician-(uncredited)",-"credit_id":-"52fe48019251416c750acb47",-"gender":-0,-"id":-1207288,-"name":-"Logan-Pithyou",-"order":-72},-{"cast_id":-93,-"character":-"Vindum-Raah-(uncredited)",-"credit_id":-"52fe48019251416c750acb4b",-"gender":-0,-"id":-1207289,-"name":-"Stuart-Pollock",-"order":-73},-{"cast_id":-94,-"character":-"Hero-(uncredited)",-"credit_id":-"52fe48019251416c750acb4f",-"gender":-0,-"id":-584868,-"name":-"Raja",-"order":-74},-{"cast_id":-95,-"character":-"Ops-Centreworker-(uncredited)",-"credit_id":-"52fe48019251416c750acb53",-"gender":-0,-"id":-1207290,-"name":-"Gareth-Ruck",-"order":-75},-{"cast_id":-96,-"character":-"Engineer-(uncredited)",-"credit_id":-"52fe48019251416c750acb57",-"gender":-0,-"id":-1062463,-"name":-"Rhian-Sheehan",-"order":-76},-{"cast_id":-97,-"character":-"Col.-Quaritch\'s-Mech-Suit-(uncredited)",-"credit_id":-"52fe48019251416c750acb5b",-"gender":-0,-"id":-60656,-"name":-"T.-J.-Storm",-"order":-77},-{"cast_id":-98,-"character":-"Female-Marine-(uncredited)",-"credit_id":-"52fe48019251416c750acb5f",-"gender":-0,-"id":-1207291,-"name":-"Jodie-Taylor",-"order":-78},-{"cast_id":-99,-"character":-"Ikran-Clan-Leader-(uncredited)",-"credit_id":-"52fe48019251416c750acb63",-"gender":-1,-"id":-1186027,-"name":-"Alicia-Vela-Bailey",-"order":-79},-{"cast_id":-100,-"character":-"Geologist-(uncredited)",-"credit_id":-"52fe48019251416c750acb67",-"gender":-0,-"id":-1207292,-"name":-"Richard-Whiteside",-"order":-80},-{"cast_id":-101,-"character":-"Na\'vi-(uncredited)",-"credit_id":-"52fe48019251416c750acb6b",-"gender":-0,-"id":-103259,-"name":-"Nikie-Zambo",-"order":-81},-{"cast_id":-102,-"character":-"Ambient-Room-Tech-/-Troupe",-"credit_id":-"52fe48019251416c750acb6f",-"gender":-1,-"id":-42286,-"name":-"Julene-Renee",-"order":-82}][{"credit_id":-"52fe48009251416c750aca23",-"department":-"Editing",-"gender":-0,-"id":-1721,-"job":-"Editor",-"name":-"Stephen-E.-Rivkin"},-{"credit_id":-"539c47ecc3a36810e3001f87",-"department":-"Art",-"gender":-2,-"id":-496,-"job":-"Production-Design",-"name":-"Rick-Carter"},-{"credit_id":-"54491c89c3a3680fb4001cf7",-"department":-"Sound",-"gender":-0,-"id":-900,-"job":-"Sound-Designer",-"name":-"Christopher-Boyes"},-{"credit_id":-"54491cb70e0a267480001bd0",-"department":-"Sound",-"gender":-0,-"id":-900,-"job":-"Supervising-Sound-Editor",-"name":-"Christopher-Boyes"},-{"credit_id":-"539c4a4cc3a36810c9002101",-"department":-"Production",-"gender":-1,-"id":-1262,-"job":-"Casting",-"name":-"Mali-Finn"},-{"credit_id":-"5544ee3b925141499f0008fc",-"department":-"Sound",-"gender":-2,-"id":-1729,-"job":-"Original-Music-Composer",-"name":-"James-Horner"},-{"credit_id":-"52fe48009251416c750ac9c3",-"department":-"Directing",-"gender":-2,-"id":-2710,-"job":-"Director",-"name":-"James-Cameron"},-{"credit_id":-"52fe48009251416c750ac9d9",-"department":-"Writing",-"gender":-2,-"id":-2710,-"job":-"Writer",-"name":-"James-Cameron"},-{"credit_id":-"52fe48009251416c750aca17",-"department":-"Editing",-"gender":-2,-"id":-2710,-"job":-"Editor",-"name":-"James-Cameron"},-{"credit_id":-"52fe48009251416c750aca29",-"department":-"Production",-"gender":-2,-"id":-2710,-"job":-"Producer",-"name":-"James-Cameron"},-{"credit_id":-"52fe48009251416c750aca3f",-"department":-"Writing",-"gender":-2,-"id":-2710,-"job":-"Screenplay",-"name":-"James-Cameron"},-{"credit_id":-"539c4987c3a36810ba0021a4",-"department":-"Art",-"gender":-2,-"id":-7236,-"job":-"Art-Direction",-"name":-"Andrew-Menzies"},-{"credit_id":-"549598c3c3a3686ae9004383",-"department":-"Visual-Effects",-"gender":-0,-"id":-6690,-"job":-"Visual-Effects-Producer",-"name":-"Jill-Brooks"},-{"credit_id":-"52fe48009251416c750aca4b",-"department":-"Production",-"gender":-1,-"id":-6347,-"job":-"Casting",-"name":-"Margery-Simkin"},-{"credit_id":-"570b6f419251417da70032fe",-"department":-"Art",-"gender":-2,-"id":-6878,-"job":-"Supervising-Art-Director",-"name":-"Kevin-Ishioka"},-{"credit_id":-"5495a0fac3a3686ae9004468",-"department":-"Sound",-"gender":-0,-"id":-6883,-"job":-"Music-Editor",-"name":-"Dick-Bernstein"},-{"credit_id":-"54959706c3a3686af3003e81",-"department":-"Sound",-"gender":-0,-"id":-8159,-"job":-"Sound-Effects-Editor",-"name":-"Shannon-Mills"},-{"credit_id":-"54491d58c3a3680fb1001ccb",-"department":-"Sound",-"gender":-0,-"id":-8160,-"job":-"Foley",-"name":-"Dennie-Thorpe"},-{"credit_id":-"54491d6cc3a3680fa5001b2c",-"department":-"Sound",-"gender":-0,-"id":-8163,-"job":-"Foley",-"name":-"Jana-Vance"},-{"credit_id":-"52fe48009251416c750aca57",-"department":-"Costume-&-Make-Up",-"gender":-1,-"id":-8527,-"job":-"Costume-Design",-"name":-"Deborah-Lynn-Scott"},-{"credit_id":-"52fe48009251416c750aca2f",-"department":-"Production",-"gender":-2,-"id":-8529,-"job":-"Producer",-"name":-"Jon-Landau"},-{"credit_id":-"539c4937c3a36810ba002194",-"department":-"Art",-"gender":-0,-"id":-9618,-"job":-"Art-Direction",-"name":-"Sean-Haworth"},-{"credit_id":-"539c49b6c3a36810c10020e6",-"department":-"Art",-"gender":-1,-"id":-12653,-"job":-"Set-Decoration",-"name":-"Kim-Sinclair"},-{"credit_id":-"570b6f2f9251413a0e00020d",-"department":-"Art",-"gender":-1,-"id":-12653,-"job":-"Supervising-Art-Director",-"name":-"Kim-Sinclair"},-{"credit_id":-"54491a6c0e0a26748c001b19",-"department":-"Art",-"gender":-2,-"id":-14350,-"job":-"Set-Designer",-"name":-"Richard-F.-Mays"},-{"credit_id":-"56928cf4c3a3684cff0025c4",-"department":-"Production",-"gender":-1,-"id":-20294,-"job":-"Executive-Producer",-"name":-"Laeta-Kalogridis"},-{"credit_id":-"52fe48009251416c750aca51",-"department":-"Costume-&-Make-Up",-"gender":-0,-"id":-17675,-"job":-"Costume-Design",-"name":-"Mayes-C.-Rubeo"},-{"credit_id":-"52fe48009251416c750aca11",-"department":-"Camera",-"gender":-2,-"id":-18265,-"job":-"Director-of-Photography",-"name":-"Mauro-Fiore"},-{"credit_id":-"5449194d0e0a26748f001b39",-"department":-"Art",-"gender":-0,-"id":-42281,-"job":-"Set-Designer",-"name":-"Scott-Herbertson"},-{"credit_id":-"52fe48009251416c750aca05",-"department":-"Crew",-"gender":-0,-"id":-42288,-"job":-"Stunts",-"name":-"Woody-Schultz"},-{"credit_id":-"5592aefb92514152de0010f5",-"department":-"Costume-&-Make-Up",-"gender":-0,-"id":-29067,-"job":-"Makeup-Artist",-"name":-"Linda-DeVetta"},-{"credit_id":-"5592afa492514152de00112c",-"department":-"Costume-&-Make-Up",-"gender":-0,-"id":-29067,-"job":-"Hairstylist",-"name":-"Linda-DeVetta"},-{"credit_id":-"54959ed592514130fc002e5d",-"department":-"Camera",-"gender":-2,-"id":-33302,-"job":-"Camera-Operator",-"name":-"Richard-Bluck"},-{"credit_id":-"539c4891c3a36810ba002147",-"department":-"Art",-"gender":-2,-"id":-33303,-"job":-"Art-Direction",-"name":-"Simon-Bright"},-{"credit_id":-"54959c069251417a81001f3a",-"department":-"Visual-Effects",-"gender":-0,-"id":-113145,-"job":-"Visual-Effects-Supervisor",-"name":-"Richard-Martin"},-{"credit_id":-"54959a0dc3a3680ff5002c8d",-"department":-"Crew",-"gender":-2,-"id":-58188,-"job":-"Visual-Effects-Editor",-"name":-"Steve-R.-Moore"},-{"credit_id":-"52fe48009251416c750aca1d",-"department":-"Editing",-"gender":-2,-"id":-58871,-"job":-"Editor",-"name":-"John-Refoua"},-{"credit_id":-"54491a4dc3a3680fc30018ca",-"department":-"Art",-"gender":-0,-"id":-92359,-"job":-"Set-Designer",-"name":-"Karl-J.-Martin"},-{"credit_id":-"52fe48009251416c750aca35",-"department":-"Camera",-"gender":-1,-"id":-72201,-"job":-"Director-of-Photography",-"name":-"Chiling-Lin"},-{"credit_id":-"52fe48009251416c750ac9ff",-"department":-"Crew",-"gender":-0,-"id":-89714,-"job":-"Stunts",-"name":-"Ilram-Choi"},-{"credit_id":-"54959c529251416e2b004394",-"department":-"Visual-Effects",-"gender":-2,-"id":-93214,-"job":-"Visual-Effects-Supervisor",-"name":-"Steven-Quale"},-{"credit_id":-"54491edf0e0a267489001c37",-"department":-"Crew",-"gender":-1,-"id":-122607,-"job":-"Dialect-Coach",-"name":-"Carla-Meyer"},-{"credit_id":-"539c485bc3a368653d001a3a",-"department":-"Art",-"gender":-2,-"id":-132585,-"job":-"